# Copied from https://medium.com/@imanmalekian31/how-to-deploy-slidev-project-on-github-pages-65d83ef8e1f1

name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Install for PDF
        run: npm i -D playwright-chromium
      - name: Build
        run: slidev build --base /bamboo/slides
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
